version: "3"

services:
  gestor-de-usuarios:
    container_name: gestor-de-usuarios
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    volumes:
      - "./src/:/home/src/"
    ports:
      - ${APP_PORT_GESTOR}:${APP_PORT_GESTOR}
    depends_on:
      - db
    networks:
      - schedula-network

  db:
    container_name: db
    image: postgres:13.2-alpine
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - schedula-network

networks:
  schedula-network:
    external: true
