name: CD

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create a docker network
        run: docker network create schedula-network

      - name: Build the Docker image
        run: docker-compose build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create a docker network
        run: docker network create schedula-network

      - name: Build the Docker image
        run: docker-compose build

      - name: Run the docker server
        run: docker-compose up -d

      - name: Run isort
        run: docker-compose run gestor-de-usuarios bash -c "isort *.py --diff"

      - name: Run Flake8
        run: docker-compose run gestor-de-usuarios bash -c "flake8"

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create a docker network
        run: docker network create schedula-network

      - name: Build the Docker image
        run: docker-compose build

      - name: Run the docker aplication
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose run gestor-de-usuarios bash -c "pytest -vv --cov"

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        run: tox -e py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: [build, lint, tests, sonarcloud]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: build-push-action
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: bigode73/gestor-de-usuarios:latest
