name: Generate Metrics Release

on:
  pull_request_review:
    types: [submitted]
    branches: 
      - main
      - develop
  release:
    types: [published]

jobs:
  send-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create Metrics SonarCloud
        run: python metrics/sonar-metrics.py ${{ github.event.repository.name }} ${{ steps.previoustag.outputs.tag }}


      - name: Commit Metrics SonarCloud File
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_USERNAME }}"
          git clone --single-branch --branch main "https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/fga-eps-mds/2022-1-schedula-doc" docs
          mkdir -p docs/analytics-raw-data
          cp -R fga-eps-mds*.json docs/analytics-raw-data
          cd docs
          git add .
          git commit -m "Métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Metrics File Generated Successfully."
